/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package category;

/**
 *
 * @author wizky
 */
public class Computer_Items extends javax.swing.JFrame {

    /**
     * Creates new form Computer_Items
     */
    public Computer_Items() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Update = new swing.ButtonGradient();
        Add = new swing.ButtonGradient();
        Cancel = new swing.ButtonGradient();
        cat_Id_Text1 = new swing.Text();
        cat_Id_Text3 = new swing.Text();
        cat_Id_Text5 = new swing.Text();
        combobox1 = new combobox.Combobox();
        combobox2 = new combobox.Combobox();
        combobox3 = new combobox.Combobox();
        jLabel2 = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Update.setText("Add");
        Update.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Update.setSizeSpeed(5.0F);
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 110, 35));

        Add.setText("Update");
        Add.setColor1(new java.awt.Color(0, 153, 0));
        Add.setColor2(new java.awt.Color(0, 102, 0));
        Add.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Add.setSizeSpeed(5.0F);
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 565, 110, 35));

        Cancel.setText("Cancel");
        Cancel.setColor1(new java.awt.Color(255, 0, 0));
        Cancel.setColor2(new java.awt.Color(153, 0, 0));
        Cancel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Cancel.setSizeSpeed(5.0F);
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 110, 35));

        cat_Id_Text1.setText("");
        getContentPane().add(cat_Id_Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 300, 40));

        cat_Id_Text3.setText("");
        getContentPane().add(cat_Id_Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 300, 40));

        cat_Id_Text5.setText("");
        getContentPane().add(cat_Id_Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 300, 40));

        combobox1.setBackground(new java.awt.Color(239, 241, 240));
        combobox1.setLabeText("Select GRN Number");
        getContentPane().add(combobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 300, 40));

        combobox2.setBackground(new java.awt.Color(239, 241, 240));
        combobox2.setLabeText("Select Location");
        getContentPane().add(combobox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 300, 40));

        combobox3.setBackground(new java.awt.Color(239, 241, 240));
        combobox3.setLabeText("Select Item Name");
        getContentPane().add(combobox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 300, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Computer_Items.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        setVisible(false);
    }//GEN-LAST:event_CancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Computer_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Computer_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Computer_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Computer_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Computer_Items().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient Add;
    private swing.ButtonGradient Cancel;
    private swing.ButtonGradient Update;
    private swing.Text cat_Id_Text1;
    private swing.Text cat_Id_Text3;
    private swing.Text cat_Id_Text5;
    private combobox.Combobox combobox1;
    private combobox.Combobox combobox2;
    private combobox.Combobox combobox3;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
