/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import com.mysql.cj.protocol.Resultset;
import java.util.logging.Level;
import java.util.logging.Logger;
import Category_Pages.Category_Choose;

/**
 *
 * @author aruna
 */
public class Login extends javax.swing.JFrame {
    JDBC.Jdbc DB = new JDBC.Jdbc();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    private void loginUser(){
        String userName = userName_txt.getText();
        String password = password_txt.getText();
        try {
            java.sql.ResultSet rs = DB.getdata("SELECT * FROM login");
            if(userName.isEmpty() || password.isEmpty()){
                System.out.println("Feild Empty");
                error_lbl.setText("Text Can't Be Empty");
            }else if(!rs.next()){
                error_lbl.setText("Account Not Found");
            }else{
                while(rs.next()){
                    String DB_userName = String.valueOf(rs.getString("username"));
                    String DB_password = String.valueOf(rs.getString("password"));
                    
                    if(DB_userName.equals(userName) && DB_password.equals(password)){
                        System.out.println("Done");
                        error_lbl.setText("Done");
                        Category_Pages.Category_Choose Main = new Category_Pages.Category_Choose();
                        Main.setVisible(true);
                        this.setVisible(false);
                        break;
                    }else{
                        System.out.println("Not Done");
                        error_lbl.setText("User Account Not Found.");
                    }
                    
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        password_txt = new swing.Password();
        userName_txt = new swing.userName_txt();
        login_btn = new swing.ButtonGradient();
        jLabel1 = new javax.swing.JLabel();
        error_lbl = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();
        To_Invento = new javax.swing.JLabel();
        Login_Here = new javax.swing.JLabel();
        SLIATE = new javax.swing.JLabel();
        manage_Y = new javax.swing.JLabel();
        Discrption = new javax.swing.JLabel();
        Dont_You2 = new javax.swing.JLabel();
        InventoLogo = new javax.swing.JLabel();
        User_Ico = new javax.swing.JLabel();
        Password_Ico = new javax.swing.JLabel();
        Dont_You3 = new javax.swing.JLabel();
        Vector = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login ");
        setResizable(false);
        setSize(new java.awt.Dimension(1120, 678));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password_txt.setText("");
        password_txt.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        jPanel1.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 240, 35));

        userName_txt.setText("");
        userName_txt.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        jPanel1.add(userName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 240, 35));

        login_btn.setText("Log In");
        login_btn.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        login_btn.setSizeSpeed(10.0F);
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        jPanel1.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 535, 110, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Main_V.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 400, 410));

        error_lbl.setFont(new java.awt.Font("Poppins SemiBold", 2, 14)); // NOI18N
        error_lbl.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(error_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, 220, 30));

        Welcome.setFont(new java.awt.Font("Poppins SemiBold", 0, 50)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setText("Welcome!");
        jPanel1.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, 60));

        To_Invento.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        To_Invento.setForeground(new java.awt.Color(255, 255, 255));
        To_Invento.setLabelFor(To_Invento);
        To_Invento.setText("TO INVENTO");
        jPanel1.add(To_Invento, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 100, 30));

        Login_Here.setFont(new java.awt.Font("Poppins SemiBold", 2, 12)); // NOI18N
        Login_Here.setForeground(new java.awt.Color(56, 64, 247));
        Login_Here.setText("Login here to continue...");
        jPanel1.add(Login_Here, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, -1, -1));

        SLIATE.setFont(new java.awt.Font("Poppins SemiBold", 3, 12)); // NOI18N
        SLIATE.setForeground(new java.awt.Color(79, 82, 255));
        SLIATE.setText("<html><font color =\"#0f187b\">The Software By :</font> SLIATE _ KANDY</html>");
        jPanel1.add(SLIATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, -1, -1));

        manage_Y.setFont(new java.awt.Font("Poppins SemiBold", 1, 15)); // NOI18N
        manage_Y.setForeground(new java.awt.Color(15, 24, 123));
        manage_Y.setText("manage your inventory easily...");
        jPanel1.add(manage_Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 250, 50));

        Discrption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Discription.png"))); // NOI18N
        jPanel1.add(Discrption, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 240, 100));

        Dont_You2.setFont(new java.awt.Font("Poppins SemiBold", 3, 12)); // NOI18N
        Dont_You2.setForeground(new java.awt.Color(79, 82, 255));
        Dont_You2.setText("Sign Up");
        Dont_You2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dont_You2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Dont_You2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Dont_You2MouseExited(evt);
            }
        });
        jPanel1.add(Dont_You2, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 590, 50, -1));

        InventoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invento_1.png"))); // NOI18N
        jPanel1.add(InventoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 330, 80));

        User_Ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 42.png"))); // NOI18N
        jPanel1.add(User_Ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 417, 30, 40));

        Password_Ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Password.png"))); // NOI18N
        jPanel1.add(Password_Ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 475, -1, 30));

        Dont_You3.setFont(new java.awt.Font("Poppins SemiBold", 3, 12)); // NOI18N
        Dont_You3.setForeground(new java.awt.Color(15, 24, 123));
        Dont_You3.setText("Don't you have an account? ");
        jPanel1.add(Dont_You3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, -1, -1));

        Vector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Path 174.png"))); // NOI18N
        Vector.setText("jLabel4");
        jPanel1.add(Vector, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 570, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 678));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed

        loginUser();
        
    }//GEN-LAST:event_login_btnActionPerformed

    private void Dont_You2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dont_You2MouseClicked
        signup.Signup s_up = new signup.Signup();
        s_up.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Dont_You2MouseClicked

    private void Dont_You2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dont_You2MouseEntered
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_Dont_You2MouseEntered

    private void Dont_You2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dont_You2MouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_Dont_You2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Discrption;
    private javax.swing.JLabel Dont_You2;
    private javax.swing.JLabel Dont_You3;
    private javax.swing.JLabel InventoLogo;
    private javax.swing.JLabel Login_Here;
    private javax.swing.JLabel Password_Ico;
    private javax.swing.JLabel SLIATE;
    private javax.swing.JLabel To_Invento;
    private javax.swing.JLabel User_Ico;
    private javax.swing.JLabel Vector;
    private javax.swing.JLabel Welcome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel error_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private swing.ButtonGradient login_btn;
    private javax.swing.JLabel manage_Y;
    private swing.Password password_txt;
    private swing.userName_txt userName_txt;
    // End of variables declaration//GEN-END:variables
}
