/* * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard;

import event.EventMenuSelected;
import form.Form_1;
import form.Form_2;
import form.Form_3;
import form.Form_4;
import form.Form_Home;
import java.awt.Color;
import javax.swing.JComponent;

/**
 *
 * @author aruna
 */
public class Mainfixed extends javax.swing.JFrame {

    /**
     * Creates new form Main_fixed
     */
    public Mainfixed() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        menu.initMoving(Mainfixed.this);
         menu.addEventMenuSelected((int index) -> {
            System.out.println(index);
            switch (index) {
                case 1:
                    header1.setVisible(false);
                    setForm(new Form_Home());
                    break;
                case 3:
                    header1.setVisible(false);
                    setForm(new Form_1());
                    break;
                case 5:
                    header1.setVisible(true);
                    setForm(new Form_2());
                    break;
                case 7:
                    header1.setVisible(false);
                    setForm(new Form_4());
                    break;
                case 9:
                    header1.setVisible(true);
                    setForm(new Form_3());
                    break;
                default:
                    break;
            }
        });
        setForm(new Form_Home());
        header1.setVisible(false);
        
    }

    
    private void setForm(JComponent com){
        mainPanal.removeAll();
        mainPanal.add(com);
        mainPanal.repaint();
        mainPanal.revalidate();
        //header1.setVisible(false);
    }
    
    public void exitWindow(){
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panalBorder1 = new swing.PanalBorder();
        menu = new component.Menu_Fixed();
        Exit_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        header1 = new component.Header();
        mainPanal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panalBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panalBorder1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        panalBorder1.setPreferredSize(new java.awt.Dimension(1024, 768));
        panalBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setPreferredSize(new java.awt.Dimension(200, 768));
        panalBorder1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 767));

        Exit_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Asset 8.png"))); // NOI18N
        Exit_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit_lblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Exit_lblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_lblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit_lblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Exit_lblMouseReleased(evt);
            }
        });
        Exit_lbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Exit_lblKeyPressed(evt);
            }
        });
        panalBorder1.add(Exit_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 16, 20, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back_Button.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panalBorder1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 40));

        header1.setPreferredSize(new java.awt.Dimension(824, 40));
        panalBorder1.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 610, 40));

        mainPanal.setOpaque(false);
        mainPanal.setPreferredSize(new java.awt.Dimension(824, 723));
        mainPanal.setLayout(new java.awt.BorderLayout());
        panalBorder1.add(mainPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 820, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panalBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panalBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void Exit_lblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Exit_lblKeyPressed

    }//GEN-LAST:event_Exit_lblKeyPressed

    private void Exit_lblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_lblMouseReleased
        Exit_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_red.png")));
    }//GEN-LAST:event_Exit_lblMouseReleased

    private void Exit_lblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_lblMousePressed
        Exit_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_white.png")));
    }//GEN-LAST:event_Exit_lblMousePressed

    private void Exit_lblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_lblMouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_Exit_lblMouseExited

    private void Exit_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_lblMouseEntered
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_Exit_lblMouseEntered

    private void Exit_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_lblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Exit_lblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainfixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainfixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainfixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainfixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainfixed().setVisible(true);
                
            }

            private void dispose() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit_lbl;
    private component.Header header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanal;
    private component.Menu_Fixed menu;
    private swing.PanalBorder panalBorder1;
    // End of variables declaration//GEN-END:variables
}
