/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RecycleBin;

import Category_Pages.*;
import category.*;

/**
 *
 * @author W I Z K Y
 */
public class ComputerItems_RB extends javax.swing.JFrame {

    /**
     * Creates new form Computer_Page
     */
    public ComputerItems_RB() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new swing.Table();
        AddIcon = new javax.swing.JLabel();
        Add = new javax.swing.JLabel();
        NotesIcon = new javax.swing.JLabel();
        Notes = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Computer Items");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setBackground(new java.awt.Color(255, 255, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "GRN", "Item Name", "Brand", "Location", "Unit Price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1100, 550));

        AddIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Profile_1_1.png"))); // NOI18N
        AddIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(AddIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 50, 50));

        Add.setFont(new java.awt.Font("Poppins SemiBold", 2, 20)); // NOI18N
        Add.setForeground(new java.awt.Color(79, 82, 255));
        Add.setText("Removed Computer Items");
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        NotesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notes_1_1.png"))); // NOI18N
        NotesIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(NotesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 50, 50));

        Notes.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Notes.setForeground(new java.awt.Color(79, 82, 255));
        Notes.setText("Notes");
        getContentPane().add(Notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        Profile.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Profile.setForeground(new java.awt.Color(79, 82, 255));
        Profile.setText("Profile");
        getContentPane().add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Removed Computer Items.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, -1, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerItems_RB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerItems_RB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerItems_RB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerItems_RB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerItems_RB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel AddIcon;
    private javax.swing.JLabel Notes;
    private javax.swing.JLabel NotesIcon;
    private javax.swing.JLabel Profile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Table table1;
    // End of variables declaration//GEN-END:variables
}
