/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import JDBC.Jdbc;
import java.awt.Cursor;
import javax.swing.table.DefaultTableModel;
import main_forms.Categories;
import main_forms.Categories_Table;
import main_forms.GRN_Table;
import main_forms.Stock_Issue_Table;
import main_forms.Employee;
import main_forms.Employee_Table;
import main_forms.Returning_Table;
import main_forms.GRN;
import main_forms.Locations;
import main_forms.Locations_Table;
import main_forms.Main_Items;
import main_forms.Main_Items_Table;
import main_forms.Removing_Type;
import main_forms.Returning;
import main_forms.Stock_Issue;
import main_forms.Supplier;
import main_forms.Supplier_Table;

/**
 *
 * @author aruna
 */

public class Form_2 extends javax.swing.JPanel {

    
    public Form_2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panalBorder1 = new swing.PanalBorder();
        Quantity_Type = new javax.swing.JLabel();
        Employee = new javax.swing.JLabel();
        Removing_type = new javax.swing.JLabel();
        Locations = new javax.swing.JLabel();
        Returning = new javax.swing.JLabel();
        Categories = new javax.swing.JLabel();
        Supplier = new javax.swing.JLabel();
        Main_Items = new javax.swing.JLabel();
        GRN = new javax.swing.JLabel();
        Stock_Issue = new javax.swing.JLabel();
        FormsBg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 242, 242));
        setPreferredSize(new java.awt.Dimension(824, 723));
        setVerifyInputWhenFocusTarget(false);

        panalBorder1.setMinimumSize(new java.awt.Dimension(824, 723));
        panalBorder1.setPreferredSize(new java.awt.Dimension(824, 713));
        panalBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Quantity_Type.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Quanityt_Type_1.png"))); // NOI18N
        Quantity_Type.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Quantity_Type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Quantity_TypeMouseClicked(evt);
            }
        });
        panalBorder1.add(Quantity_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 105, 90, 150));

        Employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Employee.png"))); // NOI18N
        Employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeeMouseEntered(evt);
            }
        });
        panalBorder1.add(Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, 130));

        Removing_type.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RemovingType.png"))); // NOI18N
        Removing_type.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Removing_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Removing_typeMouseClicked(evt);
            }
        });
        panalBorder1.add(Removing_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 100, 140));

        Locations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Locations.png"))); // NOI18N
        Locations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Locations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocationsMouseClicked(evt);
            }
        });
        panalBorder1.add(Locations, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 80, 130));

        Returning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Returning.png"))); // NOI18N
        Returning.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Returning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturningMouseClicked(evt);
            }
        });
        panalBorder1.add(Returning, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 90, 130));

        Categories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Categories_1.png"))); // NOI18N
        Categories.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Categories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriesMouseClicked(evt);
            }
        });
        panalBorder1.add(Categories, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 100, 130));

        Supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Supplier.png"))); // NOI18N
        Supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierMouseClicked(evt);
            }
        });
        panalBorder1.add(Supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 80, 130));

        Main_Items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MainItems.png"))); // NOI18N
        Main_Items.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main_ItemsMouseClicked(evt);
            }
        });
        panalBorder1.add(Main_Items, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 100, 130));

        GRN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GRN_1.png"))); // NOI18N
        GRN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GRN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRNMouseClicked(evt);
            }
        });
        panalBorder1.add(GRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 80, 130));

        Stock_Issue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StockIssue.png"))); // NOI18N
        Stock_Issue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stock_Issue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stock_IssueMouseClicked(evt);
            }
        });
        panalBorder1.add(Stock_Issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 100, 130));

        FormsBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormsBg.png"))); // NOI18N
        panalBorder1.add(FormsBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panalBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panalBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMouseEntered

    }//GEN-LAST:event_EmployeeMouseEntered

    private void EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMouseClicked
        Employee_Table frm = new Employee_Table();
        frm.setVisible(true);
    }//GEN-LAST:event_EmployeeMouseClicked

    private void SupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierMouseClicked
        Supplier_Table frm = new Supplier_Table();
        frm.setVisible(true);
    }//GEN-LAST:event_SupplierMouseClicked

    private void LocationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationsMouseClicked
        Locations_Table frm = new Locations_Table();
        frm.setVisible(true);
    }//GEN-LAST:event_LocationsMouseClicked

    private void CategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriesMouseClicked
        Categories_Table frm = new Categories_Table();
        frm.setVisible(true);
    }//GEN-LAST:event_CategoriesMouseClicked

    private void Main_ItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_ItemsMouseClicked
        Main_Items_Table  frm = new Main_Items_Table();
        frm.setVisible(true);
    }//GEN-LAST:event_Main_ItemsMouseClicked

    private void GRNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNMouseClicked
        GRN_Table frm = new GRN_Table();
        frm.setVisible(true);
    }//GEN-LAST:event_GRNMouseClicked

    private void Stock_IssueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_IssueMouseClicked
        Stock_Issue_Table frm = new Stock_Issue_Table();
        frm.setVisible(true);
    }//GEN-LAST:event_Stock_IssueMouseClicked

    private void ReturningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturningMouseClicked
        Returning_Table frm = new Returning_Table();
        frm.setVisible(true);
    }//GEN-LAST:event_ReturningMouseClicked

    private void Removing_typeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Removing_typeMouseClicked

        Removing_Type frm = new Removing_Type();
        frm.setVisible(true);
    }//GEN-LAST:event_Removing_typeMouseClicked

    private void Quantity_TypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Quantity_TypeMouseClicked
        main_forms.QuantityType_Table QT = new main_forms.QuantityType_Table();
        QT.setVisible(true);
    }//GEN-LAST:event_Quantity_TypeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Categories;
    private javax.swing.JLabel Employee;
    private javax.swing.JLabel FormsBg;
    private javax.swing.JLabel GRN;
    private javax.swing.JLabel Locations;
    private javax.swing.JLabel Main_Items;
    private javax.swing.JLabel Quantity_Type;
    private javax.swing.JLabel Removing_type;
    private javax.swing.JLabel Returning;
    private javax.swing.JLabel Stock_Issue;
    private javax.swing.JLabel Supplier;
    private swing.PanalBorder panalBorder1;
    // End of variables declaration//GEN-END:variables

    private void setCursor(int HAND_CURSOR) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
