/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

/**
 *
 * @author aruna
 */
public class Form_3 extends javax.swing.JPanel {

    /**
     * Creates new form form1
     */
    public Form_3() {
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panalBorder1 = new swing.PanalBorder();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 242, 242));
        setPreferredSize(new java.awt.Dimension(824, 723));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panalBorder1.setPreferredSize(new java.awt.Dimension(824, 713));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/About_Us_Background_2.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout panalBorder1Layout = new javax.swing.GroupLayout(panalBorder1);
        panalBorder1.setLayout(panalBorder1Layout);
        panalBorder1Layout.setHorizontalGroup(
            panalBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalBorder1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panalBorder1Layout.setVerticalGroup(
            panalBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panalBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 723));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private swing.PanalBorder panalBorder1;
    // End of variables declaration//GEN-END:variables
}
