/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package form;

import main_forms.Employee;
import category.*;

/**
 *
 * @author aruna
 */

public class Form_1 extends javax.swing.JPanel {

    dashboard.Mainfixed main = new dashboard.Mainfixed();
    component.Header search = new component.Header();
    /**
     * Creates new form form1
     */
    public Form_1() {
        initComponents(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panalBorder1 = new swing.PanalBorder();
        jPanel1 = new javax.swing.JPanel();
        computerBtn = new swing.ButtonGradient();
        electricBtn = new swing.ButtonGradient();
        furnitureBtn = new swing.ButtonGradient();
        vehicaleBtn = new swing.ButtonGradient();
        jLabel3 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 242, 242));
        setPreferredSize(new java.awt.Dimension(824, 733));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panalBorder1.setPreferredSize(new java.awt.Dimension(824, 733));
        panalBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        computerBtn.setText("Computer Items");
        computerBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 15)); // NOI18N
        computerBtn.setSizeSpeed(10.0F);
        computerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                computerBtnMouseClicked(evt);
            }
        });
        computerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(computerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 45));

        electricBtn.setText("Electric Items");
        electricBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 15)); // NOI18N
        electricBtn.setSizeSpeed(10.0F);
        electricBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricBtnActionPerformed(evt);
            }
        });
        jPanel1.add(electricBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 270, 45));

        furnitureBtn.setText("Furniture Items");
        furnitureBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 15)); // NOI18N
        furnitureBtn.setSizeSpeed(10.0F);
        furnitureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                furnitureBtnActionPerformed(evt);
            }
        });
        jPanel1.add(furnitureBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 270, 45));

        vehicaleBtn.setText("Vehicles");
        vehicaleBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 15)); // NOI18N
        vehicaleBtn.setSizeSpeed(10.0F);
        vehicaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicaleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(vehicaleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 270, 45));

        panalBorder1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 590, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Category_Page_1.png"))); // NOI18N
        panalBorder1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 470, 330));

        Title.setFont(new java.awt.Font("Poppins SemiBold", 0, 40)); // NOI18N
        Title.setForeground(new java.awt.Color(56, 64, 247));
        Title.setText("Categories");
        panalBorder1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 230, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background_Image.png"))); // NOI18N
        panalBorder1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 824, 730));

        add(panalBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 722));
    }// </editor-fold>//GEN-END:initComponents

    private void computerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerBtnActionPerformed
        Category_Pages.Computer_Page computer = new Category_Pages.Computer_Page();
        computer.setVisible(true);
        
    }//GEN-LAST:event_computerBtnActionPerformed

    private void electricBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricBtnActionPerformed
        Category_Pages.Electric_Page electronic = new Category_Pages.Electric_Page();
        electronic.setVisible(true);
    }//GEN-LAST:event_electricBtnActionPerformed

    private void furnitureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_furnitureBtnActionPerformed
        Category_Pages.Furniture_Page furniture = new Category_Pages.Furniture_Page();
        furniture.setVisible(true);
    }//GEN-LAST:event_furnitureBtnActionPerformed

    private void vehicaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicaleBtnActionPerformed
        Category_Pages.Vehicles_Page vehicles = new Category_Pages.Vehicles_Page();
        vehicles.setVisible(true);
    }//GEN-LAST:event_vehicaleBtnActionPerformed

    private void computerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_computerBtnMouseClicked
        
    }//GEN-LAST:event_computerBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private swing.ButtonGradient computerBtn;
    private swing.ButtonGradient electricBtn;
    private swing.ButtonGradient furnitureBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private swing.PanalBorder panalBorder1;
    private swing.ButtonGradient vehicaleBtn;
    // End of variables declaration//GEN-END:variables
}
