/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

/**
 *
 * @author wizky
 */
public class Profile_Frm extends javax.swing.JPanel {

    /**
     * Creates new form Profile_Frm
     */
    public Profile_Frm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Save = new swing.ButtonGradient();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Save.setText("Save");
        Save.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Save.setSizeSpeed(5.0F);
        add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 630, 110, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UserProfile.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 830, 740));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient Save;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
