/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Category_Pages;

import category.*;
import RecycleBin.*;
import dashboard.*;

/**
 *
 * @author W I Z K Y
 */
public class Category_Choose extends javax.swing.JFrame {

    /**
     * Creates new form Computer_Page
     */
    public Category_Choose() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FixedAssests = new swing.ButtonGradient();
        Stationary = new swing.ButtonGradient();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Computer Items");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FixedAssests.setText("Fixed Assests");
        FixedAssests.setToolTipText("");
        FixedAssests.setFont(new java.awt.Font("Poppins SemiBold", 0, 17)); // NOI18N
        FixedAssests.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FixedAssests.setSizeSpeed(8.0F);
        FixedAssests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FixedAssestsMouseClicked(evt);
            }
        });
        FixedAssests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FixedAssestsActionPerformed(evt);
            }
        });
        getContentPane().add(FixedAssests, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 310, 40));

        Stationary.setText("Stationary Items");
        Stationary.setToolTipText("");
        Stationary.setFont(new java.awt.Font("Poppins SemiBold", 0, 17)); // NOI18N
        Stationary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Stationary.setSizeSpeed(8.0F);
        Stationary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StationaryActionPerformed(evt);
            }
        });
        getContentPane().add(Stationary, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 310, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Category Choose Bg1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, -1, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FixedAssestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FixedAssestsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FixedAssestsActionPerformed

    private void StationaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StationaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StationaryActionPerformed

    private void FixedAssestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FixedAssestsMouseClicked
        dashboard.Mainfixed Main = new dashboard.Mainfixed();
        Main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FixedAssestsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Category_Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Category_Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Category_Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Category_Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Category_Choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient FixedAssests;
    private swing.ButtonGradient Stationary;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
