/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Category_Pages;

import category.*;
import RecycleBin.*;
import Notes.Ele_Notes;


/**
 *
 * @author W I Z K Y
 */
public class Electric_Page extends javax.swing.JFrame {

    /**
     * Creates new form Computer_Page
     */
    public Electric_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new swing.Table();
        Add = new javax.swing.JLabel();
        Add_Icon = new javax.swing.JLabel();
        Remove = new javax.swing.JLabel();
        RefreshIcon = new javax.swing.JLabel();
        Update = new javax.swing.JLabel();
        Update_Icon = new javax.swing.JLabel();
        Recycle_Bin = new javax.swing.JLabel();
        NotesIcon = new javax.swing.JLabel();
        Notes = new javax.swing.JLabel();
        RecycleBin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Electronic Items");
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setBackground(new java.awt.Color(255, 255, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "GRN", "Item Name", "Brand", "Location", "Unit Price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1100, 550));

        Add.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Add.setForeground(new java.awt.Color(79, 82, 255));
        Add.setText("Add");
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 110, -1, -1));

        Add_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add_Ico.png"))); // NOI18N
        Add_Icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_IconMouseClicked(evt);
            }
        });
        getContentPane().add(Add_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 50));

        Remove.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Remove.setForeground(new java.awt.Color(79, 82, 255));
        Remove.setText("Remove");
        getContentPane().add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 110, 60, -1));

        RefreshIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Remove_Ico.png"))); // NOI18N
        RefreshIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RefreshIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 50, 50, 50));

        Update.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(79, 82, 255));
        Update.setText("Update");
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 110, -1, -1));

        Update_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh Ico.png"))); // NOI18N
        Update_Icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Update_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 50, 50, 50));

        Recycle_Bin.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Recycle_Bin.setForeground(new java.awt.Color(79, 82, 255));
        Recycle_Bin.setText("Recycle Bin");
        getContentPane().add(Recycle_Bin, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 110, -1, -1));

        NotesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notes_1_1.png"))); // NOI18N
        NotesIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NotesIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NotesIconMouseClicked(evt);
            }
        });
        getContentPane().add(NotesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 50, 50));

        Notes.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Notes.setForeground(new java.awt.Color(79, 82, 255));
        Notes.setText("Notes");
        getContentPane().add(Notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, -1, -1));

        RecycleBin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bin.png"))); // NOI18N
        RecycleBin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RecycleBin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecycleBinMouseClicked(evt);
            }
        });
        getContentPane().add(RecycleBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 50, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Electric_Items.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, -1, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Add_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_IconMouseClicked
        Electric_Items frm = new Electric_Items();
        frm.setVisible(true);
    }//GEN-LAST:event_Add_IconMouseClicked

    private void RecycleBinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecycleBinMouseClicked
       ElectricItems_RB frm = new ElectricItems_RB();
       frm.setVisible(true);
    }//GEN-LAST:event_RecycleBinMouseClicked

    private void NotesIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotesIconMouseClicked
        Ele_Notes frm = new Ele_Notes();
        frm.setVisible(true);
    }//GEN-LAST:event_NotesIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Electric_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Electric_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Electric_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Electric_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Electric_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Add_Icon;
    private javax.swing.JLabel Notes;
    private javax.swing.JLabel NotesIcon;
    private javax.swing.JLabel RecycleBin;
    private javax.swing.JLabel Recycle_Bin;
    private javax.swing.JLabel RefreshIcon;
    private javax.swing.JLabel Remove;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel Update_Icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Table table1;
    // End of variables declaration//GEN-END:variables
}
