/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_forms;

import java.awt.Color;


/**
 *
 * @author aruna
 */
public class Categories extends javax.swing.JFrame {

    /**
     * Creates new form Main_Items
     */
    private void textClear(){
        cat_Id_Text.setText("");
        cat_Name_Text.setText("");
        cat_Description_Txt.setText("");
    }
    JDBC.Jdbc DB = new JDBC.Jdbc();
    public Categories() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cancel = new swing.ButtonGradient();
        updateBtn = new swing.ButtonGradient();
        addBtn = new swing.ButtonGradient();
        errorLbl = new javax.swing.JLabel();
        cat_Id_Text = new swing.Text();
        cat_Name_Text = new swing.Text();
        jScrollPane2 = new javax.swing.JScrollPane();
        cat_Description_Txt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cancel.setText("Cancel");
        Cancel.setColor1(new java.awt.Color(255, 0, 0));
        Cancel.setColor2(new java.awt.Color(153, 0, 0));
        Cancel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Cancel.setSizeSpeed(5.0F);
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 110, 35));

        updateBtn.setText("Update");
        updateBtn.setColor1(new java.awt.Color(0, 153, 0));
        updateBtn.setColor2(new java.awt.Color(0, 102, 0));
        updateBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        updateBtn.setSizeSpeed(5.0F);
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 565, 110, 35));

        addBtn.setText("Add");
        addBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        addBtn.setSizeSpeed(5.0F);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 110, 35));

        errorLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        errorLbl.setForeground(new java.awt.Color(255, 0, 51));
        errorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(errorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 370, 40));

        cat_Id_Text.setText("");
        getContentPane().add(cat_Id_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 150, 380, 40));

        cat_Name_Text.setText("");
        getContentPane().add(cat_Name_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 250, 380, 40));

        cat_Description_Txt.setBackground(new java.awt.Color(239, 241, 240));
        cat_Description_Txt.setColumns(20);
        cat_Description_Txt.setRows(5);
        cat_Description_Txt.setBorder(null);
        jScrollPane2.setViewportView(cat_Description_Txt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 370, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CategoryForm.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 830, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        setVisible(false);
    }//GEN-LAST:event_CancelMouseClicked

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String ID = cat_Id_Text.getText();
        String Name = cat_Name_Text.getText();
        String Des = cat_Description_Txt.getText();
        
        if(ID.equals("")){
            errorLbl.setForeground(Color.red);
            errorLbl.setText("ID is Empty!!!");
        }else if(Name.equals("")){
            errorLbl.setForeground(Color.red);
            errorLbl.setText("Name is Empty!!!");
        }else{
            try {
                if (Des.equals("")){
                    String empty = "Empty";
                    DB.putdata("INSERT INTO main_category VALUES('"+ID+"','"+Name+"','"+empty+"')");
                    errorLbl.setForeground(Color.GREEN);
                    errorLbl.setText("Done");
                    textClear();
                }else{
                    DB.putdata("INSERT INTO main_category VALUES('"+ID+"','"+Name+"','"+Des+"')");
                    errorLbl.setForeground(Color.GREEN);
                    errorLbl.setText("Done");
                    textClear();
                }
                
            } catch (Exception e) {
                String exceptionClassName = e.getClass().getName();
                System.out.println(exceptionClassName);
                if (exceptionClassName.equals("java.sql.SQLException")){
                    errorLbl.setForeground(Color.red);
                    errorLbl.setText("Only Numbers for ID!!!");
                    textClear();
                }else if (exceptionClassName.equals("java.sql.SQLIntegrityConstraintViolationException")){
                    errorLbl.setForeground(Color.red);
                    errorLbl.setText("ID Already Exists");
                    textClear();
                }
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient Cancel;
    private swing.ButtonGradient addBtn;
    private javax.swing.JTextArea cat_Description_Txt;
    private swing.Text cat_Id_Text;
    private swing.Text cat_Name_Text;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private swing.ButtonGradient updateBtn;
    // End of variables declaration//GEN-END:variables
}
