/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_forms;

/**
 *
 * @author W I Z K Y
 */
public class GRN extends javax.swing.JFrame {

    /**
     * Creates new form GRN
     */
    public GRN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Update = new swing.ButtonGradient();
        Add = new swing.ButtonGradient();
        Cancel = new swing.ButtonGradient();
        grnId = new swing.Text();
        grnNumber1 = new swing.Text();
        total = new swing.Text();
        serialNumber2 = new swing.Text();
        quantity1 = new swing.Text();
        unitPrice1 = new swing.Text();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Update.setText("Add");
        Update.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Update.setSizeSpeed(5.0F);
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 110, 35));

        Add.setText("Update");
        Add.setColor1(new java.awt.Color(0, 153, 0));
        Add.setColor2(new java.awt.Color(0, 102, 0));
        Add.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Add.setSizeSpeed(5.0F);
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 110, 35));

        Cancel.setText("Cancel");
        Cancel.setColor1(new java.awt.Color(255, 0, 0));
        Cancel.setColor2(new java.awt.Color(153, 0, 0));
        Cancel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Cancel.setSizeSpeed(5.0F);
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 640, 110, 35));

        grnId.setText("");
        grnId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnIdActionPerformed(evt);
            }
        });
        getContentPane().add(grnId, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 150, 290, 40));

        grnNumber1.setText("");
        getContentPane().add(grnNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 250, 290, 40));

        total.setText("");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 290, 40));

        serialNumber2.setText("");
        getContentPane().add(serialNumber2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 290, 40));

        quantity1.setText("");
        getContentPane().add(quantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 290, -1));

        unitPrice1.setText("");
        getContentPane().add(unitPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 290, 40));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 345, 290, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 445, 290, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 280, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GRN.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void grnIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grnIdActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GRN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient Add;
    private swing.ButtonGradient Cancel;
    private swing.ButtonGradient Update;
    private swing.Text grnId;
    private swing.Text grnNumber1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private swing.Text quantity1;
    private swing.Text serialNumber2;
    private swing.Text total;
    private swing.Text unitPrice1;
    // End of variables declaration//GEN-END:variables
}
