/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_forms;

import RecycleBin.*;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author W I Z K Y
 */
public class Locations_Table extends javax.swing.JFrame {

    /**
     * Creates new form Categories_Form
     */
    JDBC.Jdbc DB = new JDBC.Jdbc();
    public Locations_Table() {
        initComponents();
        locationTbl.getTableHeader().setFont(new Font("Poppins Medium", Font.PLAIN, 12));
        locationTbl.getTableHeader().setOpaque(true);
        locationTbl.getTableHeader().setBackground(Color.decode("#6D87FF"));
        locationTbl.getTableHeader().setForeground(Color.BLACK);
        locationTbl.setRowHeight(25);
        tableDataClear();
        tableDataLoader();
    }
    
    private void tableDataClear(){
        try {
            while (0<=locationTbl.getRowCount()){
                DefaultTableModel table = (DefaultTableModel)locationTbl.getModel();
                table.removeRow(locationTbl.getRowCount()-1);
            }
        } catch (Exception e) {
            System.out.println("tableDataClear: "+e);
        }
    }
    
    private void tableDataLoader (){
        try {
            java.sql.ResultSet rs = DB.getdata("SELECT * FROM location");   
            while (rs.next()){
                String ID = String.valueOf(rs.getString("Location_ID"));
                String Name = String.valueOf(rs.getString("Location_Name"));
                String Des = String.valueOf(rs.getString("Discription"));
                
                
                
                String table_data[] = {ID,Name,Des};
                DefaultTableModel table = (DefaultTableModel)locationTbl.getModel();
                
                table.addRow(table_data);
            
        }
            
        } catch (Exception e) {
            System.out.println("Error(tableDataLoader): "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_Icon = new javax.swing.JLabel();
        Add = new javax.swing.JLabel();
        RefreshIcon = new javax.swing.JLabel();
        Remove = new javax.swing.JLabel();
        Update_Icon = new javax.swing.JLabel();
        Update = new javax.swing.JLabel();
        RecycleBin = new javax.swing.JLabel();
        Recycle_Bin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        locationTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add_Ico.png"))); // NOI18N
        Add_Icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_IconMouseClicked(evt);
            }
        });
        getContentPane().add(Add_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 50, 50));

        Add.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Add.setForeground(new java.awt.Color(79, 82, 255));
        Add.setText("Add");
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 120, -1, -1));

        RefreshIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Remove_Ico.png"))); // NOI18N
        RefreshIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RefreshIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 60, 50, 50));

        Remove.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Remove.setForeground(new java.awt.Color(79, 82, 255));
        Remove.setText("Remove");
        getContentPane().add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 60, -1));

        Update_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh Ico.png"))); // NOI18N
        Update_Icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_IconMouseClicked(evt);
            }
        });
        getContentPane().add(Update_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 50, 50));

        Update.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(79, 82, 255));
        Update.setText("Update");
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        RecycleBin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bin.png"))); // NOI18N
        RecycleBin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RecycleBin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecycleBinMouseClicked(evt);
            }
        });
        getContentPane().add(RecycleBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 60, 50, 50));

        Recycle_Bin.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Recycle_Bin.setForeground(new java.awt.Color(79, 82, 255));
        Recycle_Bin.setText("Recycle Bin");
        getContentPane().add(Recycle_Bin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        jScrollPane1.setOpaque(false);

        locationTbl.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        locationTbl.setForeground(new java.awt.Color(51, 51, 51));
        locationTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Location ID", "Location Name", "Description"
            }
        ));
        locationTbl.setGridColor(new java.awt.Color(0, 0, 0));
        locationTbl.setRowHeight(20);
        locationTbl.setSelectionBackground(new java.awt.Color(199, 227, 228));
        locationTbl.setSelectionForeground(new java.awt.Color(0, 0, 0));
        locationTbl.setShowHorizontalLines(false);
        locationTbl.setShowVerticalLines(false);
        jScrollPane1.setViewportView(locationTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 750, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LocationTableBg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 830, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Add_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_IconMouseClicked
        Locations frm = new Locations();
        frm.setVisible(true);

    }//GEN-LAST:event_Add_IconMouseClicked

    private void RecycleBinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecycleBinMouseClicked
        Location_RB frm = new Location_RB();
        frm.setVisible(true);
    }//GEN-LAST:event_RecycleBinMouseClicked

    private void Update_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_IconMouseClicked
        tableDataClear();
        tableDataLoader();
    }//GEN-LAST:event_Update_IconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Locations_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Locations_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Locations_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Locations_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Locations_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Add_Icon;
    private javax.swing.JLabel RecycleBin;
    private javax.swing.JLabel Recycle_Bin;
    private javax.swing.JLabel RefreshIcon;
    private javax.swing.JLabel Remove;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel Update_Icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable locationTbl;
    // End of variables declaration//GEN-END:variables
}
