/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_forms;

/**
 *
 * @author aruna
 */
public class Removing_Type extends javax.swing.JFrame {

    /**
     * Creates new form Main_Items
     */
    public Removing_Type() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Update = new swing.ButtonGradient();
        Add = new swing.ButtonGradient();
        Cancel = new swing.ButtonGradient();
        removeTypeName = new swing.Text();
        removeTypeId1 = new swing.Text();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Update.setText("Add");
        Update.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Update.setSizeSpeed(5.0F);
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 110, 35));

        Add.setText("Update");
        Add.setColor1(new java.awt.Color(0, 153, 0));
        Add.setColor2(new java.awt.Color(0, 102, 0));
        Add.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Add.setSizeSpeed(5.0F);
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 565, 110, 35));

        Cancel.setText("Cancel");
        Cancel.setColor1(new java.awt.Color(255, 0, 0));
        Cancel.setColor2(new java.awt.Color(153, 0, 0));
        Cancel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Cancel.setSizeSpeed(5.0F);
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 110, 35));

        removeTypeName.setText("");
        removeTypeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTypeNameActionPerformed(evt);
            }
        });
        getContentPane().add(removeTypeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 260, 320, 40));

        removeTypeId1.setText("");
        getContentPane().add(removeTypeId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 155, 320, 40));

        jScrollPane1.setBackground(new java.awt.Color(239, 241, 240));

        jTextArea1.setBackground(new java.awt.Color(239, 241, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 310, 310));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RemovingForm.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void removeTypeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTypeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeTypeNameActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Removing_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Removing_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Removing_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Removing_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Removing_Type().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient Add;
    private swing.ButtonGradient Cancel;
    private swing.ButtonGradient Update;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private swing.Text removeTypeId1;
    private swing.Text removeTypeName;
    // End of variables declaration//GEN-END:variables
}
