/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_forms;

/**
 *
 * @author W I Z K Y
 */
public class Returning extends javax.swing.JFrame {

    /**
     * Creates new form Returning
     */
    public Returning() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Update = new swing.ButtonGradient();
        Add = new swing.ButtonGradient();
        Cancel = new swing.ButtonGradient();
        text2 = new swing.Text();
        text3 = new swing.Text();
        text4 = new swing.Text();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Update.setText("Add");
        Update.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Update.setSizeSpeed(5.0F);
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 110, 35));

        Add.setText("Update");
        Add.setColor1(new java.awt.Color(0, 153, 0));
        Add.setColor2(new java.awt.Color(0, 102, 0));
        Add.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Add.setSizeSpeed(5.0F);
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 565, 110, 35));

        Cancel.setText("Cancel");
        Cancel.setColor1(new java.awt.Color(255, 0, 0));
        Cancel.setColor2(new java.awt.Color(153, 0, 0));
        Cancel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Cancel.setSizeSpeed(5.0F);
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 110, 35));

        text2.setText("");
        getContentPane().add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 270, 40));

        text3.setText("");
        getContentPane().add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 270, 40));

        text4.setText("");
        getContentPane().add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 270, 40));

        jTextArea1.setBackground(new java.awt.Color(239, 241, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 280, 250));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ReturningForm.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 824, 722));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Returning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Returning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Returning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Returning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Returning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient Add;
    private swing.ButtonGradient Cancel;
    private swing.ButtonGradient Update;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private swing.Text text2;
    private swing.Text text3;
    private swing.Text text4;
    // End of variables declaration//GEN-END:variables
}
