/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_forms;

/**
 *
 * @author aruna
 */
public class Stock_Issue extends javax.swing.JFrame {

    /**
     * Creates new form Main_Items
     */
    public Stock_Issue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cancel2 = new swing.ButtonGradient();
        Add = new swing.ButtonGradient();
        Update = new swing.ButtonGradient();
        text2 = new swing.Text();
        text6 = new swing.Text();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cancel2.setText("Cancel");
        Cancel2.setColor1(new java.awt.Color(255, 0, 0));
        Cancel2.setColor2(new java.awt.Color(153, 0, 0));
        Cancel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Cancel2.setSizeSpeed(5.0F);
        Cancel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cancel2MouseClicked(evt);
            }
        });
        Cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel2ActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 110, 35));

        Add.setText("Update");
        Add.setColor1(new java.awt.Color(0, 153, 0));
        Add.setColor2(new java.awt.Color(0, 102, 0));
        Add.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Add.setSizeSpeed(5.0F);
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 565, 110, 35));

        Update.setText("Add");
        Update.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        Update.setSizeSpeed(5.0F);
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 110, 35));

        text2.setText("");
        getContentPane().add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 290, 40));

        text6.setText("");
        getContentPane().add(text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 290, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 280, 40));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 280, 40));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 280, 40));

        jScrollPane1.setBackground(new java.awt.Color(239, 241, 240));

        jTextArea1.setBackground(new java.awt.Color(239, 241, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 290, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SIN.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancel2ActionPerformed

    private void Cancel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel2MouseClicked
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_Cancel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock_Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock_Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock_Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock_Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock_Issue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient Add;
    private swing.ButtonGradient Cancel2;
    private swing.ButtonGradient Update;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private swing.Text text2;
    private swing.Text text6;
    // End of variables declaration//GEN-END:variables
}
