/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_forms;

import JDBC.Jdbc;
import java.awt.Color;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aruna
 */
public class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Main_Items
     */
    public Supplier() {
        initComponents();
    }
    private void textClear(){
        supIdTxt.setText("");
        registerNumberTxt.setText("");
        nameTxt.setText("");
        addressTxt.setText("");
        phoneNumberTxt.setText("");
        idTxt.setText("");
        disTxt.setText("");
    }
    JDBC.Jdbc DB = new Jdbc();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBtn = new swing.ButtonGradient();
        updateBtn = new swing.ButtonGradient();
        cancelBtn = new swing.ButtonGradient();
        supIdTxt = new swing.Text();
        registerNumberTxt = new swing.Text();
        nameTxt = new swing.Text();
        addressTxt = new swing.Text();
        phoneNumberTxt = new swing.Text();
        idTxt = new swing.Text();
        errorLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        disTxt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setText("Add");
        addBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        addBtn.setSizeSpeed(5.0F);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 110, 35));

        updateBtn.setText("Update");
        updateBtn.setColor1(new java.awt.Color(0, 153, 0));
        updateBtn.setColor2(new java.awt.Color(0, 102, 0));
        updateBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        updateBtn.setSizeSpeed(5.0F);
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 565, 110, 35));

        cancelBtn.setText("Cancel");
        cancelBtn.setColor1(new java.awt.Color(255, 0, 0));
        cancelBtn.setColor2(new java.awt.Color(153, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        cancelBtn.setSizeSpeed(5.0F);
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 110, 35));

        supIdTxt.setText("");
        getContentPane().add(supIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 300, 40));

        registerNumberTxt.setText("");
        getContentPane().add(registerNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 300, 40));

        nameTxt.setText("");
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 300, 40));

        addressTxt.setText("");
        getContentPane().add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 300, 40));

        phoneNumberTxt.setText("");
        getContentPane().add(phoneNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 535, 300, 40));

        idTxt.setText("");
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, 300, 40));

        errorLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        errorLbl.setForeground(new java.awt.Color(255, 0, 51));
        errorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(errorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, 280, 30));

        disTxt.setBackground(new java.awt.Color(239, 241, 240));
        disTxt.setColumns(20);
        disTxt.setRows(5);
        jScrollPane1.setViewportView(disTxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 260, 220));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SuppliersForm.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String ID = supIdTxt.getText();
        String regNo = registerNumberTxt.getText();
        String Name = nameTxt.getText();
        String Address = addressTxt.getText();
        String TP = phoneNumberTxt.getText();
        String NIC = idTxt.getText();
        String Des = disTxt.getText();
        
        if(ID.equals("")){
            errorLbl.setForeground(Color.red);
            errorLbl.setText("ID is Empty!!!");
        }else if(Name.equals("")){
            errorLbl.setForeground(Color.red);
            errorLbl.setText("Name is Empty!!!");
        }else if(Address.equals("")){
            errorLbl.setForeground(Color.red);
            errorLbl.setText("Address is Empty!!!");
        }else if(TP.equals("")){
            errorLbl.setForeground(Color.red);
            errorLbl.setText("Telephone Number is Empty!!!");
        }else if(NIC.equals("")){
            errorLbl.setForeground(Color.red);
            errorLbl.setText("NIC is Empty!!!");
        }else{
            try {
                if (Des.equals("") && regNo.equals("")){
                    String empty = "Empty";
                    DB.putdata("INSERT INTO supplier VALUES('"+ID+"','"+empty+"','"+Name+"','"+NIC+"','"+Address+"','"+TP+"','"+empty+"')");
                    errorLbl.setForeground(Color.GREEN);
                    errorLbl.setText("Done");
                    textClear();
                }else if (Des.equals("")||!regNo.equals("")){
                    String empty = "Empty";
                    DB.putdata("INSERT INTO supplier VALUES('"+ID+"','"+regNo+"','"+Name+"','"+NIC+"','"+Address+"','"+TP+"','"+empty+"')");
                    errorLbl.setForeground(Color.GREEN);
                    errorLbl.setText("Done");
                    textClear();
                }else if (!Des.equals("")||regNo.equals("")){
                    String empty = "Empty";
                    DB.putdata("INSERT INTO supplier VALUES('"+ID+"','"+empty+"','"+Name+"','"+NIC+"','"+Address+"','"+TP+"','"+Des+"')");
                    errorLbl.setForeground(Color.GREEN);
                    errorLbl.setText("Done");
                    textClear();
                }else{
                    DB.putdata("INSERT INTO supplier VALUES('"+ID+"','"+regNo+"','"+Name+"','"+NIC+"','"+Address+"','"+TP+"','"+Des+"')");
                    errorLbl.setForeground(Color.GREEN);
                    errorLbl.setText("Done");
                    textClear();
                }
                
            } catch (Exception e) {
                String exceptionClassName = e.getClass().getName();
                System.out.println(exceptionClassName);
                if (exceptionClassName.equals("java.sql.SQLException")){
                    errorLbl.setForeground(Color.red);
                    errorLbl.setText("Only Numbers for ID!!!");
                    textClear();
                }else if (exceptionClassName.equals("java.sql.SQLIntegrityConstraintViolationException")){
                    errorLbl.setForeground(Color.red);
                    errorLbl.setText("ID Already Exists");
                    textClear();
                }
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient addBtn;
    private swing.Text addressTxt;
    private swing.ButtonGradient cancelBtn;
    private javax.swing.JTextArea disTxt;
    private javax.swing.JLabel errorLbl;
    private swing.Text idTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Text nameTxt;
    private swing.Text phoneNumberTxt;
    private swing.Text registerNumberTxt;
    private swing.Text supIdTxt;
    private swing.ButtonGradient updateBtn;
    // End of variables declaration//GEN-END:variables
}
