-- MySQL Script generated by MySQL Workbench
-- Wed Oct 12 22:40:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventory_management_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventory_management_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventory_management_system` DEFAULT CHARACTER SET utf8 ;
USE `inventory_management_system` ;

-- -----------------------------------------------------
-- Table `inventory_management_system`.`empolyee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`empolyee` (
  `Emp_ID` INT NOT NULL,
  `Emp_Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(200) NULL DEFAULT NULL,
  `NIC` VARCHAR(45) NOT NULL,
  `Contact_Number` INT NOT NULL,
  `Discription` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`Emp_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`main_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`main_category` (
  `Cat_ID` INT NOT NULL,
  `Cat_Name` VARCHAR(45) NOT NULL,
  `Discription` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`Cat_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`main_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`main_items` (
  `Main_Item_ID` INT NOT NULL,
  `Main_Item_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Main_Cat_ID` INT NOT NULL,
  `Discription` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`Main_Item_ID`, `Main_Cat_ID`),
  INDEX `fk_Sub_Category_Main_Category_idx` (`Main_Cat_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Sub_Category_Main_Category`
    FOREIGN KEY (`Main_Cat_ID`)
    REFERENCES `inventory_management_system`.`main_category` (`Cat_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`quantity_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`quantity_type` (
  `Quantity_Type_ID` INT NOT NULL,
  `Quantity_Type_Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  PRIMARY KEY (`Quantity_Type_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`supplier` (
  `Sup_ID` INT NOT NULL,
  `Supplier_Register_ID` VARCHAR(45) NULL DEFAULT NULL,
  `Sup_Name` VARCHAR(45) NOT NULL,
  `NIC` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(200) NOT NULL,
  `Contact_Number` INT NOT NULL,
  `Discription` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`Sup_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`good_receiving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`good_receiving` (
  `GRN_ID` INT NOT NULL,
  `GRN_Number` VARCHAR(20) NOT NULL,
  `Serial_Number` VARCHAR(45) NULL DEFAULT NULL,
  `Date` DATE NOT NULL,
  `Unit_Price` DOUBLE NOT NULL,
  `Quantity_Liq` DOUBLE NOT NULL,
  `Quantity_Solid` INT NOT NULL,
  `Total` DOUBLE NOT NULL,
  `Discription` VARCHAR(200) NULL DEFAULT NULL,
  `Main_Items_Main_Item_ID` INT NOT NULL,
  `Supplier_Sup_ID` INT NOT NULL,
  `Quantity_Type_Quantity_Type_ID` INT NOT NULL,
  PRIMARY KEY (`GRN_ID`, `Main_Items_Main_Item_ID`, `Supplier_Sup_ID`, `Quantity_Type_Quantity_Type_ID`),
  INDEX `fk_Good_Receiving_Main_Items1_idx` (`Main_Items_Main_Item_ID` ASC) VISIBLE,
  INDEX `fk_Good_Receiving_Supplier1_idx` (`Supplier_Sup_ID` ASC) VISIBLE,
  INDEX `fk_Good_Receiving_Quantity_Type1_idx` (`Quantity_Type_Quantity_Type_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Good_Receiving_Main_Items1`
    FOREIGN KEY (`Main_Items_Main_Item_ID`)
    REFERENCES `inventory_management_system`.`main_items` (`Main_Item_ID`),
  CONSTRAINT `fk_Good_Receiving_Quantity_Type1`
    FOREIGN KEY (`Quantity_Type_Quantity_Type_ID`)
    REFERENCES `inventory_management_system`.`quantity_type` (`Quantity_Type_ID`),
  CONSTRAINT `fk_Good_Receiving_Supplier1`
    FOREIGN KEY (`Supplier_Sup_ID`)
    REFERENCES `inventory_management_system`.`supplier` (`Sup_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`items` (
  `date` DATE NOT NULL,
  `Brand` VARCHAR(45) NULL DEFAULT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `Quntity` INT NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Total` VARCHAR(45) NOT NULL,
  `good_receiving_GRN_ID` INT NOT NULL,
  `good_receiving_Main_Items_Main_Item_ID` INT NOT NULL,
  PRIMARY KEY (`date`, `good_receiving_GRN_ID`, `good_receiving_Main_Items_Main_Item_ID`),
  INDEX `fk_Items_good_receiving1_idx` (`good_receiving_GRN_ID` ASC, `good_receiving_Main_Items_Main_Item_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Items_good_receiving1`
    FOREIGN KEY (`good_receiving_GRN_ID` , `good_receiving_Main_Items_Main_Item_ID`)
    REFERENCES `inventory_management_system`.`good_receiving` (`GRN_ID` , `Main_Items_Main_Item_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`location` (
  `Location_ID` INT NOT NULL,
  `Location_Name` VARCHAR(45) NOT NULL,
  `Discription` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`Location_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`login` (
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`removing_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`removing_type` (
  `Removing_Type_ID` INT NOT NULL,
  `Removing_Type_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Removing_Type_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`removing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`removing` (
  `Removing_ID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Qunatity` INT NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Discription` VARCHAR(200) NULL DEFAULT NULL,
  `Removing_Type_Removing_Type_ID` INT NOT NULL,
  `Main_Items_Main_Item_ID` INT NOT NULL,
  PRIMARY KEY (`Removing_ID`, `Removing_Type_Removing_Type_ID`, `Main_Items_Main_Item_ID`),
  INDEX `fk_Removing_Removing_Type1_idx` (`Removing_Type_Removing_Type_ID` ASC) VISIBLE,
  INDEX `fk_Removing_Main_Items1_idx` (`Main_Items_Main_Item_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Removing_Main_Items1`
    FOREIGN KEY (`Main_Items_Main_Item_ID`)
    REFERENCES `inventory_management_system`.`main_items` (`Main_Item_ID`),
  CONSTRAINT `fk_Removing_Removing_Type1`
    FOREIGN KEY (`Removing_Type_Removing_Type_ID`)
    REFERENCES `inventory_management_system`.`removing_type` (`Removing_Type_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`stock_issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`stock_issue` (
  `Stock_Issue_ID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Quantity` INT NOT NULL,
  `Discription` VARCHAR(200) NULL DEFAULT NULL,
  `Location_Location_ID` INT NOT NULL,
  `Empolyee_Emp_ID` INT NOT NULL,
  `Good_Receiving_GRN_ID` INT NOT NULL,
  PRIMARY KEY (`Stock_Issue_ID`, `Location_Location_ID`, `Empolyee_Emp_ID`, `Good_Receiving_GRN_ID`),
  INDEX `fk_Stock_Issue_Location1_idx` (`Location_Location_ID` ASC) VISIBLE,
  INDEX `fk_Stock_Issue_Empolyee1_idx` (`Empolyee_Emp_ID` ASC) VISIBLE,
  INDEX `fk_Stock_Issue_Good_Receiving1_idx` (`Good_Receiving_GRN_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_Issue_Empolyee1`
    FOREIGN KEY (`Empolyee_Emp_ID`)
    REFERENCES `inventory_management_system`.`empolyee` (`Emp_ID`),
  CONSTRAINT `fk_Stock_Issue_Good_Receiving1`
    FOREIGN KEY (`Good_Receiving_GRN_ID`)
    REFERENCES `inventory_management_system`.`good_receiving` (`GRN_ID`),
  CONSTRAINT `fk_Stock_Issue_Location1`
    FOREIGN KEY (`Location_Location_ID`)
    REFERENCES `inventory_management_system`.`location` (`Location_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventory_management_system`.`return`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management_system`.`return` (
  `Return_Stock_Number` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Quantity` INT NOT NULL,
  `Discription` VARCHAR(200) NULL DEFAULT NULL,
  `Stock_Issue_Stock_Issue_ID` INT NOT NULL,
  PRIMARY KEY (`Return_Stock_Number`, `Stock_Issue_Stock_Issue_ID`),
  INDEX `fk_Return_Stock_Issue1_idx` (`Stock_Issue_Stock_Issue_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Return_Stock_Issue1`
    FOREIGN KEY (`Stock_Issue_Stock_Issue_ID`)
    REFERENCES `inventory_management_system`.`stock_issue` (`Stock_Issue_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
