/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Stationary_Items;

import Notes.*;

/**
 *
 * @author W I Z K Y
 */
public class Stationary_Items extends javax.swing.JFrame {

    /**
     * Creates new form Computer_Page
     */
    public Stationary_Items() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new swing.Table();
        Add = new javax.swing.JLabel();
        RemoveIcon = new javax.swing.JLabel();
        Remove = new javax.swing.JLabel();
        RefreshIcon = new javax.swing.JLabel();
        Refresh = new javax.swing.JLabel();
        RecycleBinIcon = new javax.swing.JLabel();
        Recycle_Bin = new javax.swing.JLabel();
        NotesIcon = new javax.swing.JLabel();
        Notes = new javax.swing.JLabel();
        ProfileIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Computer Items");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setBackground(new java.awt.Color(255, 255, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "GRN", "Item Name", "Brand", "Location", "Unit Price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1100, 540));

        Add.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Add.setForeground(new java.awt.Color(79, 82, 255));
        Add.setText("Add");
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 110, -1, -1));

        RemoveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add_Ico.png"))); // NOI18N
        getContentPane().add(RemoveIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 50));

        Remove.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Remove.setForeground(new java.awt.Color(79, 82, 255));
        Remove.setText("Remove");
        getContentPane().add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 110, 70, -1));

        RefreshIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Remove_Ico.png"))); // NOI18N
        getContentPane().add(RefreshIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 50, 50, 50));

        Refresh.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Refresh.setForeground(new java.awt.Color(79, 82, 255));
        Refresh.setText("Refresh");
        getContentPane().add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        RecycleBinIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh Ico.png"))); // NOI18N
        getContentPane().add(RecycleBinIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 50, 50));

        Recycle_Bin.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Recycle_Bin.setForeground(new java.awt.Color(79, 82, 255));
        Recycle_Bin.setText("Removed Items");
        getContentPane().add(Recycle_Bin, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 110, -1, -1));

        NotesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notes_1_1.png"))); // NOI18N
        NotesIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NotesIconMouseClicked(evt);
            }
        });
        getContentPane().add(NotesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 50, 50));

        Notes.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        Notes.setForeground(new java.awt.Color(79, 82, 255));
        Notes.setText("Notes");
        getContentPane().add(Notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, -1, -1));

        ProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bin.png"))); // NOI18N
        getContentPane().add(ProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stationary_Items1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, -1, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NotesIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotesIconMouseClicked
        Stationary_Items frm = new Stationary_Items();
        frm.setVisible(true);
    }//GEN-LAST:event_NotesIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stationary_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stationary_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stationary_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stationary_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stationary_Items().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Notes;
    private javax.swing.JLabel NotesIcon;
    private javax.swing.JLabel ProfileIcon;
    private javax.swing.JLabel RecycleBinIcon;
    private javax.swing.JLabel Recycle_Bin;
    private javax.swing.JLabel Refresh;
    private javax.swing.JLabel RefreshIcon;
    private javax.swing.JLabel Remove;
    private javax.swing.JLabel RemoveIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Table table1;
    // End of variables declaration//GEN-END:variables
}
